### ISSUE TITLE
See all the thrL and thrH for all the variables when we have many variables 

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#129]
When we load many variables ( ~ more than 10), the software does not allow you to see the whole list of variables with the corresponding thrH and thrL for each weather type. It would be nice to have an "arrow" or a tool to be able to move to the right and see all the variables. See picture as an example of the issue. 
![WT_code_thrL_thrH](https://user-images.githubusercontent.com/69871426/101147113-d7ef6100-3613-11eb-8c6b-df37e98a4641.png)

**Comment by ATimHewson** [comment]
I agree with the suggestion of Esti to make this scrollable with an arrow or equivalent. However _in addition_ we could potentially drop the letters "thr" from the threshold column names to narrow the space taken by each column, so that e.g. SWVL3_thrL becomes SWVL3_L. Fatima thinks this would be OK!

**Comment by onyb** [comment]
The excel-like sheet is something that's very hard to control, but this is the best I could come up with. Note that in the case with few columns, the full grid will take the smallest shape possible. It might look a bit odd, but it was necessary because the table-width now adjusts dynamically based on the number of columns.

## With few columns

<img width="1418" alt="Screenshot 2020-12-11 at 02 07 28" src="https://user-images.githubusercontent.com/3684187/101848398-af0c2600-3b55-11eb-949e-bd0c3beacb04.png">

## With many columns

<img width="1415" alt="Screenshot 2020-12-11 at 02 08 40" src="https://user-images.githubusercontent.com/3684187/101848444-cba85e00-3b55-11eb-8002-7a50c6c66576.png">

**Comment by EstiGascon** [comment]
Many thanks! I think this could be fine, what do you think @ATimHewson @AugustinVintzileos , @FatimaPillosu? An important question, can we see the "arrow" or tool to merge different weather types when we move to the right of the table? That was one of the most critical part, as when we had so many variables, we could not merge weather types.

**Comment by onyb** [comment]
> can we see the "arrow" or tool to merge different weather types when we move to the right of the table

Yes, absolutely. You just have to scroll to the right of the table.

**Comment by EstiGascon** [comment]
Many thanks! This is exactly what we wanted.

**Comment by onyb** [comment]
Fixed in [v0.17.0](https://github.com/esowc/ecPoint-Calibrate/releases/tag/v0.17.0).
