### ISSUE TITLE
Issue with v 0.16.0

### ISSUE THREAD

**Issue by AugustinVintzileos** [esowc/ecPoint-Calibrate#131]
Both Esti and I had the same issue when working for the first time with v 0.16.0. At the first try we couldn't read the predictants/predictors. We had to stop the program and restart it. Restarting it on the same shell window didn't help though. We needed to start a new konsole and relaunch the code to be successful.  Also, in order to change the units of the predictants we still need to change the value of one of the arithmetic operators.

**Comment by onyb** [comment]
Regarding the first part of your issue, it could be because the release was quite big and required a long download. In such cases, the GUI may start before the backend is ready to serve requests. Subsequent launches should be fine. Let me know if this is something you see every time.

Regarding the second issue about units, is it same as https://github.com/esowc/ecPoint-Calibrate/issues/128?
